{"name": "test_zjc_WorkLists_002", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''160846' AND `userId`  '306' AND `inDate`  '20210518'' at line 1\")", "trace": "self = <test_assistantappKwCases.Test_assistantapp object at 0x7f7f92573880>\n\n    @allure.feature(\"门店任务-取消任务\")\n    @allure.severity(\"blocker\")\n    def test_zjc_WorkLists_002(self):\n    \t# 读取yaml文件\n    \tyamlFile = ckw.CommonKeyWord().Yaml_Read(\"/Users/zoudw/PycharmProjects/automan/testFile/ZhangJunChao/zjctest.yaml\")\n    \t# 读取yaml里手机号\n    \tmobile = ckw.CommonKeyWord().Yaml_GetByKey(yamlFile,\"mobileAssistant\")\n    \t# 读取Yaml登录密码\n    \tpassword = ckw.CommonKeyWord().Yaml_GetByKey(yamlFile,\"password\")\n    \t# 读取Yaml执行环节\n    \tenv = ckw.CommonKeyWord().Yaml_GetByKey(yamlFile,\"env\")\n    \t# 登录获取token-调取接口\n    \tloginRes = bkw.assistantappApi_UserLogin({\"header\":{\"Content-Type\": \"application/json;charsetUTF-8\"},\"parma\":{},\"data\":{\"mobile\":mobile,\"code\":password},\"env\":env},\"dict\")\n    \t# 登录获取token-提取token\n    \ttoken = ckw.CommonKeyWord().Json_GetJsonValue(loginRes,[[\"data\",\"token\"]])\n    \t# 登录获取userid-提取userid\n    \tuserid = ckw.CommonKeyWord().Json_GetJsonValue(loginRes,[[\"data\",\"id\"]])\n    \t# 打印token到控制台\n    \tckw.CommonKeyWord().Print_ToControl(\"token：\",token)\n    \t# 打印token到日志\n    \tckw.CommonKeyWord().Print_ToLog(\"token：\",token)\n    \t# 读取yaml文件\n    \tyamlFile = ckw.CommonKeyWord().Yaml_Read(\"/Users/zoudw/PycharmProjects/automan/testFile/ZhangJunChao/zjctest.yaml\")\n    \t# 读取yaml查询任务数据idsql\n    \tGetCanceldsql = ckw.CommonKeyWord().Yaml_GetByKey(yamlFile,\"GetCanceld\")\n    \t# 打印查询结果到控制台\n    \tckw.CommonKeyWord().Print_ToControl(\"Canceldsql：\",GetCanceldsql)\n    \t# 打印查询结果到日志\n    \tckw.CommonKeyWord().Print_ToLog(\"Canceldsql：\",GetCanceldsql)\n    \t# mysql执行查询-查询取消任务id\n>   \tGetCanceld = ckw.CommonKeyWord().Db_MysqlSelect({\"host\":\"udtest.uniondrug.com\",\"port\":\"6033\",\"username\":\"develop\",\"password\":\"develop123\",\"database\":\"cn_uniondrug_module_assistant\",\"sql\":\"SELECT id FROM `cn_uniondrug_module_assistant`.`work_list` WHERE `storeId`  '160846' AND `userId`  '306' AND `inDate`  '20210518';\"})\n\ntestCase/assistantapp/test_assistantappKwCases.py:2065: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nKeyWordDriver/CommonKeyWord.py:113: in Db_MysqlSelect\n    cursor.execute(sql)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/cursors.py:170: in execute\n    result = self._query(query)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/cursors.py:328: in _query\n    conn.query(q)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/connections.py:517: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/connections.py:732: in _read_query_result\n    result.read()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/connections.py:1075: in read\n    first_packet = self.connection._read_packet()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/connections.py:684: in _read_packet\n    packet.check_error()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndata = b\"\\xff(\\x04#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''160846' AND `userId`  '306' AND `inDate`  '20210518'' at line 1\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''160846' AND `userId`  '306' AND `inDate`  '20210518'' at line 1\")\n\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymysql/err.py:109: ProgrammingError"}, "attachments": [{"name": "log", "source": "69503b9a-d7eb-47fb-9dbc-49c7a8391c58-attachment.txt", "type": "text/plain"}], "start": 1621497201251, "stop": 1621497201478, "uuid": "bb6090e3-14df-4e70-a2b7-093c425c1d97", "historyId": "e862ac5b108ac3a9d372b8eea5a117b6", "testCaseId": "976d816553d53c1b9c6d0578e9182350", "fullName": "testCase.assistantapp.test_assistantappKwCases.Test_assistantapp#test_zjc_WorkLists_002", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "门店任务-取消任务"}, {"name": "parentSuite", "value": "testCase.assistantapp"}, {"name": "suite", "value": "test_assistantappKwCases"}, {"name": "subSuite", "value": "Test_assistantapp"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "2646-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.assistantapp.test_assistantappKwCases"}]}