{"name": "test_zjc_AssistantLists_003", "status": "broken", "statusDetails": {"message": "yaml.scanner.ScannerError: mapping values are not allowed here\n  in \"<unicode string>\", line 129, column 14:\n      videostatus:\n                 ^", "trace": "self = <test_assistantappKwCases.Test_assistantapp object at 0x7f9ec60d4850>\n\n    @allure.feature(\"店员管理-店员调店\")\n    @allure.severity(\"blocker\")\n    def test_zjc_AssistantLists_003(self):\n    \t# 读取yaml文件\n>   \tyamlFile = ckw.CommonKeyWord().Yaml_Read(\"/Users/zoudw/PycharmProjects/automan/testFile/ZhangJunChao/zjctest.yaml\")\n\ntestCase/assistantapp/test_assistantappKwCases.py:1889: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nKeyWordDriver/CommonKeyWord.py:80: in Yaml_Read\n    y = yaml.load(f.read())\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/__init__.py:114: in load\n    return loader.get_single_data()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/constructor.py:49: in get_single_data\n    node = self.get_single_node()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/composer.py:36: in get_single_node\n    document = self.compose_document()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/composer.py:55: in compose_document\n    node = self.compose_node(None, None)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/composer.py:127: in compose_mapping_node\n    while not self.check_event(MappingEndEvent):\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/parser.py:98: in check_event\n    self.current_event = self.state()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/parser.py:428: in parse_block_mapping_key\n    if self.check_token(KeyToken):\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/scanner.py:116: in check_token\n    self.fetch_more_tokens()\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/scanner.py:223: in fetch_more_tokens\n    return self.fetch_value()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <yaml.loader.FullLoader object at 0x7f9ec60d4100>\n\n    def fetch_value(self):\n    \n        # Do we determine a simple key?\n        if self.flow_level in self.possible_simple_keys:\n    \n            # Add KEY.\n            key = self.possible_simple_keys[self.flow_level]\n            del self.possible_simple_keys[self.flow_level]\n            self.tokens.insert(key.token_number-self.tokens_taken,\n                    KeyToken(key.mark, key.mark))\n    \n            # If this key starts a new block mapping, we need to add\n            # BLOCK-MAPPING-START.\n            if not self.flow_level:\n                if self.add_indent(key.column):\n                    self.tokens.insert(key.token_number-self.tokens_taken,\n                            BlockMappingStartToken(key.mark, key.mark))\n    \n            # There cannot be two simple keys one after another.\n            self.allow_simple_key = False\n    \n        # It must be a part of a complex key.\n        else:\n    \n            # Block context needs additional checks.\n            # (Do we really need them? They will be caught by the parser\n            # anyway.)\n            if not self.flow_level:\n    \n                # We are allowed to start a complex value if and only if\n                # we can start a simple key.\n                if not self.allow_simple_key:\n>                   raise ScannerError(None, None,\n                            \"mapping values are not allowed here\",\n                            self.get_mark())\nE                   yaml.scanner.ScannerError: mapping values are not allowed here\nE                     in \"<unicode string>\", line 129, column 14:\nE                         videostatus:\nE                                    ^\n\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/scanner.py:577: ScannerError"}, "start": 1621577034107, "stop": 1621577034123, "uuid": "549705f0-3fcb-4b6e-8c5f-f8892fc0108c", "historyId": "b0e8004f22ef37fb2a64019fb2afd16f", "testCaseId": "75b2c010e5e20470ea9f2f346a5e24ed", "fullName": "testCase.assistantapp.test_assistantappKwCases.Test_assistantapp#test_zjc_AssistantLists_003", "labels": [{"name": "feature", "value": "店员管理-店员调店"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "testCase.assistantapp"}, {"name": "suite", "value": "test_assistantappKwCases"}, {"name": "subSuite", "value": "Test_assistantapp"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "6524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.assistantapp.test_assistantappKwCases"}]}